name: Check Tasks YAMLs

"on":
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        # actions/checkout@v4.4.0
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          fetch-depth: 0

      - name: Create k8s Kind Cluster
        # helm/kind-action@v1.12.0
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3
        with:
          cluster_name: kind

      - name: Set up Tekton
        # tektoncd/actions/setup-tektoncd@main
        uses: tektoncd/actions/setup-tektoncd@2b126ef971bbfda195d8a6c9b7c4eb3bfda452bf
        with:
          pipeline_version: v1.16.0

      - name: Apply all Task & Pipeline YAMLs
        run: |
          set -e
          ./.github/scripts/check_task_yamls.sh
